# Hardware: Dell Inspiron 16 7630 2-in-1 (Intel 13th gen / Raptor Lake-U,
# Iris Xe, Intel AX211 Wi-Fi + Bluetooth, Intel SOF audio, NVMe).
#
# This is hand-written rather than generated by nixos-generate-config, because
# the ISO is built in CI before the laptop is ever seen. If you re-run
# nixos-generate-config on the machine, take its `boot.initrd.*` and kernel
# module additions as the source of truth and merge them in here.
{ config, lib, pkgs, ... }:

{
  # Without this the installed system gets no linux-firmware, no sof-firmware
  # and no alsa-firmware: Wi-Fi and audio work in the live ISO (which sets
  # enableAllHardware) and then disappear on first boot of the installed system.
  hardware.enableRedistributableFirmware = true;

  hardware.cpu.intel.updateMicrocode = true;

  # Iris Xe VA-API. intel-media-driver is the Gen12+ (iHD) driver — the older
  # intel-vaapi-driver is pre-Broadwell only and would be wrong here.
  # enable must be explicit: nothing on a Wayland-only Hyprland session turns it
  # on for us, and without it /run/opengl-driver never gets populated.
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      vpl-gpu-rt
    ];
  };

  # Stage-1 needs these to find and mount root; the installer ISO's hardware
  # detection does not carry over to the installed system.
  boot.initrd.availableKernelModules = [
    "nvme"
    "btrfs"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "i915"
  ];
  boot.kernelModules = [ "kvm-intel" ];

  # disko emits fileSystems for every subvolume but does not mark any of them
  # neededForBoot, so /nix and /var/log must be mounted in stage-1 explicitly.
  fileSystems."/nix".neededForBoot = true;
  fileSystems."/var/log".neededForBoot = true;

  # Laptop power and thermal management.
  services.thermald.enable = true;
  services.power-profiles-daemon.enable = true;
  services.upower.enable = true;
  # Without disk swap HybridSleep is not achievable, so power off instead of
  # suspending into a swap device that does not exist.
  services.upower.criticalPowerAction = "PowerOff";

  # Firmware updates via LVFS. Capsule updates need a real EFI variable, which
  # is why boot.loader.efi.canTouchEfiVariables is true in configuration.nix,
  # and EspLocation defaults to efiSysMountPoint (/boot, where disko puts it).
  services.fwupd.enable = true;

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
}
